name: Build_and_run_test

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - dev

jobs:
  build_and_run_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Build
        run: mvn clean package -DskipTests

      - name: Tests
        run: mvn test

  deploy:
    needs: build_and_run_test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install WireGuard
        run: sudo apt-get update && sudo apt-get install -y wireguard

      - name: Configure WireGuard
        run: |
          echo "${{ secrets.WG_CLIENT_PRIVATE_KEY }}" > client_privatekey
          sudo chmod 600 client_privatekey

          sudo tee /etc/wireguard/wg0.conf > /dev/null <<EOT
          [Interface]
          PrivateKey = $(cat client_privatekey)
          Address = 10.0.0.2/24

          [Peer]
          PublicKey = Pkn+JmxsALijCINMu8UCzWz2T1VMaurF+OiVYD0EGWk=
          Endpoint = ${{ secrets.VPN_SERVER_IP }}:51820
          AllowedIPs = 0.0.0.0/0
          PersistentKeepalive = 25
          EOT

          sudo wg-quick up wg0

      - name: Deploy to VPS over VPN
        run: |
          ssh user@10.0.0.1 'bash -s' < ./deploy.sh